services:
  - type: web
    name: wildsafe-ml-service
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PRELOAD_MODEL
        value: "false"
      - key: ORCHESTRATOR_ALERT_URL
        value: https://smart-wild.onrender.com/alert
